In [1]:
import numpy as np

#### 1) Write a program to find and manipulate the shape of ndarray.

In [2]:

arr = np.array( [[ 1, 2, 3],[ 4, 5, 6]] )
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


#### 2) Write a program to find the logarithmic value of numbers from 31 to 40.  

In [3]:
  

array = [31,32,33,34,35,36,37,38,39,40]
print ("Input array : ", array)
array2 = np.log(array)
print ("Output array : ", array2)

Input array :  [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
Output array :  [3.4339872  3.4657359  3.49650756 3.52636052 3.55534806 3.58351894
 3.61091791 3.63758616 3.66356165 3.68887945]


#### 3) Write a program to create a 3x2 matrix containing zeros and another matrix containing one only.

In [4]:

=>
ix ba = np.zeros([3, 2], dtype = int) 
print("Matrix a : \n", a) 
print("\n")
b = np.ones([3, 2], dtype =int)
print("Matr : \n", b)

SyntaxError: invalid syntax (Temp/ipykernel_10024/2344653589.py, line 1)

#### 4) Write a program to convert regular array into an ndarray.

In [6]:
l =["mahi","jangid","vinod","aditya"]
x= np.array(l)
print(x)
print(type(x))

['mahi' 'jangid' 'vinod' 'aditya']
<class 'numpy.ndarray'>


#### 5) Write a program to create an ndarray containing characters of a string.

In [ ]:
arr = np.array([['apple', 'banana', 'cherry'],['mango','chikoo', 'strawberry']])
print(arr)
print(type(arr))

#### 6) Write a program to find transpose of two metrics and then perform addition on them.

In [12]:
X = [[5,7], [1,10], [11,15]]
Y = [0, 0, 0], [0, 0, 0]
print(X)        
print(Y)
print()
for i in range (len (X)):
    for j in range (len (X[0])):
        Y [j][i] = X [i][j]
for j in Y:
    print (j)

print()
for i in range(len(A)): 
     for j in range(len(A[0])):
        result[i][j] = A[i][j] + B[i][j]
for R in result:
    print(R)

[[5, 7], [1, 10], [11, 15]]
([0, 0, 0], [0, 0, 0])

[5, 1, 11]
[7, 10, 15]

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


#### 7) Write a program to explain various string manipulation methods on Numpy arrays.

In [ ]:
# numpy.lower() function
print(np.char.lower(['TIRTHAN', 'SHAH']))
# numpy.split() function
print(np.char.split('tirthan h shah'))
# numpy.join() function
print(np.char.join('-', 'tirthan'))
# numpy.add() function
print(np.char.add(['hello'],[' xyz']) )
# numpy.multiply() function
print(np.char.multiply('Hello ',3))
# numpy.center() function
print(np.char.center('hello', 20,fillchar = '*'))
# numpy.capitalize() function
print(np.char.capitalize('hello world'))
# numpy.title() function
print(np.char.title('hello how are you?'))
# numpy.upper() function
print(np.char.upper(['hello','world']))
# numpy.splitlines() function
print(np.char.splitlines('hello\nhow are you?') )
# numpy.replace() function
print(np.char.replace('He is a bad boy', 'is', 'was'))
# numpy.decode() function
a = np.char.encode('hello', 'cp500') 
print(a) 
print(np.char.decode(a,'cp500'))
# numpy.encode() function
a = np.char.encode('hello', 'cp500') 
print(a)

#### 8) Write a program to perform various arithmetic functions on Numpy arrays.

In [14]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print( 'First array:' )
print( a) 
print ('\n')  

print ('Second array:' )
b = np.array([10,10,10]) 
print (b )
print ('\n')  

print ('Add the two arrays:' )
print (np.add(a,b) )
print ('\n')  

print ('Subtract the two arrays:' )
print (np.subtract(a,b) )
print ('\n'  )

print ('Multiply the two arrays:' )
print (np.multiply(a,b) )
print ('\n'  )

print ('Divide the two arrays:' )
print (np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


#### 9) Write a program to explain matrix manipulation using ndarrays.

In [15]:
x = np.array([[11, 12], [20, 14]])
y = np.array([[5, 9], [11, 12]])
  
# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (np.add(x,y))
  
# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (np.subtract(x,y))
  
# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (np.divide(x,y))

# using multiply() to multiply matrices element wise
print ("The element wise multiplication of matrix is : ")
print (np.multiply(x,y))
  
# using dot() to multiply matrices
print ("The product of matrices is : ")
print (np.dot(x,y))

# using sqrt() to print the square root of matrix
print ("The element wise square root is : ")
print (np.sqrt(x))
  
# using sum() to print summation of all elements of matrix
print ("The summation of all matrix element is : ")
print (np.sum(y))
  
# using sum(axis=0) to print summation of all columns of matrix
print ("The column wise summation of all matrix  is : ")
print (np.sum(y,axis=0))
  
# using sum(axis=1) to print summation of all columns of matrix
print ("The row wise summation of all matrix  is : ")
print (np.sum(y,axis=1))
  
# using "T" to transpose the matrix
print ("The transpose of given matrix is : ")
print (x.T)


The element wise addition of matrix is : 
[[16 21]
 [31 26]]
The element wise subtraction of matrix is : 
[[6 3]
 [9 2]]
The element wise division of matrix is : 
[[2.2        1.33333333]
 [1.81818182 1.16666667]]
The element wise multiplication of matrix is : 
[[ 55 108]
 [220 168]]
The product of matrices is : 
[[187 243]
 [254 348]]
The element wise square root is : 
[[3.31662479 3.46410162]
 [4.47213595 3.74165739]]
The summation of all matrix element is : 
37
The column wise summation of all matrix  is : 
[16 21]
The row wise summation of all matrix  is : 
[14 23]
The transpose of given matrix is : 
[[11 20]
 [12 14]]


#### 10) Assume That You have this Array [ [ 5 , 10 , 15 ] , [ 20 , 12 , 28 ]] , Now At output give Only that Value which is Greater Than 12 .

In [16]:
x =np.array([[5 , 10 , 15 ] ,[20,12,28]])
print(x)
x[x>12]

[[ 5 10 15]
 [20 12 28]]


array([15, 20, 28])

#### 11) Generate the Normally distributed data using the numpy function.







#### 12) W.A.P to get the largest elements of the given array using numpy .

In [17]:
def largest(arr,n):
    return (max(arr))
arr = [25, 424, 545, 190, 980]
n = len(arr)
Ans = largest(arr,n)
print ("Largest in given array is",Ans)

Largest in given array is 980


#### 13) Write the Code to find the mean across the dimension Of the below matrix.[[ 10 , 20 ,30 ] , [ 11 ,22 ,33] , [111,222,333]]

In [ ]:

=>
x = np.array([[ 10 , 20 ,30 ] , [ 11 ,22 ,33] , [111,222,333]])
print("Original array:")
print(x)
print("Mean of each column:")
print(x.mean(axis=0))
print("Mean of each row:")
print(x.mean(axis=1))


#### 14) Replace all the value less than 5 with 5 in given array . [ 8, 7, -5, 6, 0, 3, 2, 90 ,10 ]

In [ ]:
array = np.array([ 8, 7, -5, 6, 0, 3, 2, 90 ,10 ])

array[array < 5] = 5
print(array)

#### 15) Check Whether [2,5,6] is present in [22,55,2,66,5,6]

In [ ]:
arr1 = [22,55,2,66,5,6]
arr2 = [2,5,6]
m = len(arr1) 
n = len(arr2) 
s = set()
for i in range(m) :
    s.add(arr1[i])
    
p = len(s)
for i in range(n) :
    s.add(arr2[i])
if (len(s) == p) :
    print("arr2[] is subset of arr1[] ")
else :
    print("arr2[] is not subset of arr1[] ")
