In [1]:
import numpy as np

In [2]:
# nd - number of dymension

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,"mahi","aditya",4+5j])   # *** 4+5k is not working why 

array(['1', '2', '3', '4', 'mahi', 'aditya', '(4+5j)'], dtype='<U64')

In [6]:
np.array([[3,4],[6,7]])

array([[3, 4],
       [6, 7]])

In [7]:
np.array([[3,4],[6,7],[1,2]])

array([[3, 4],
       [6, 7],
       [1, 2]])

In [8]:
# np.array([[3,4],[6,7],[1,2,3]])

In [9]:
np.array([[[3,4],[6,7]],[[1,2],[4,5]]])

array([[[3, 4],
        [6, 7]],

       [[1, 2],
        [4, 5]]])

In [10]:
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [11]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
np.array([(4,5),(6,4)])

array([[4, 5],
       [6, 4]])

In [13]:
np.array([(4,5),[6,4]])

array([[4, 5],
       [6, 4]])

In [14]:
arr = np.array([(1,2),(3,4)],dtype=[("a",'<f2'),("b",'<f8')]) # f = float f2 = 16, f8 =64
arr = np.array([(1,2),(3,4)],dtype=[("a",'<i2'),("b",'<i8')]) # i = int  i2 = 16 , i8 = 64
# for menegment of memory 
# i2    16
# i4    32 bydefault
# i8    64

In [15]:
type(arr[0][0])
type(arr[0][1])

numpy.int64

In [16]:
arr = np.array([[3,4],[6,7]])
arr

array([[3, 4],
       [6, 7]])

In [17]:
# arr[0]
# arr[0][1]

In [18]:
np.mat(arr)

matrix([[3, 4],
        [6, 7]])

In [19]:
l = [3,4,5,6,7]
np.array(l)

array([3, 4, 5, 6, 7])

In [20]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [21]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [22]:
arr = np.matrix([[3,4],[6,7]])
np.asanyarray(arr)  #The metrix is not conveted into array.
# np.array(arr)
# np.asarray(arr)   # The np.array,  np.asarray is conver matrix into array but asanyarray is no converted into array.
# matrix is the sunset of array .and the list is not subset of list

matrix([[3, 4],
        [6, 7]])

In [23]:
issubclass(np.matrix,np.ndarray)  #The matrix is subset of array 
issubclass(np.ndarray,np.matrix) # the array is not subset of matrix 

False

In [24]:
arr = np.array([[3,4],[6,7]])
a = arr
a
# mutteble
# shollo copy
b = np.copy(arr)
b
# inmutteble
# create the new place in a memory and it's called deep copy or  

array([[3, 4],
       [6, 7]])

In [25]:
arr[0][0] = 67
arr

array([[67,  4],
       [ 6,  7]])

In [26]:
a # The a is effected

array([[67,  4],
       [ 6,  7]])

In [27]:
b # The b is not effected

array([[3, 4],
       [6, 7]])

In [28]:
for i in arr:
    print(i)


[67  4]
[6 7]


In [29]:
np.fromfunction(lambda i ,j   :i==j ,(4,4))   # row and clm row(0,1,2,3) clm (0,1,2,3)


array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [30]:
type(np.fromfunction(lambda i ,j   :i==j ,(4,4)))

numpy.ndarray

In [31]:
np.fromfunction(lambda i ,j   :i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
(i* i for i in range(5))

<generator object <genexpr> at 0x0000019FB6467E40>

In [33]:
[i* i for i in range(5)]

[0, 1, 4, 9, 16]

In [34]:
def test(x):
    yield x

In [35]:
test(5)

<generator object test at 0x0000019FB648D270>

In [36]:
gen =[i * i for i in range(5)]
print(gen)

[0, 1, 4, 9, 16]


In [37]:
np.fromiter(gen,dtype= int)
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

In [38]:
gen
for i in  gen:
    print(i)

0
1
4
9
16


In [39]:
np.fromstring("1,2,3,4,5" ,sep= ",", dtype=int)

array([1, 2, 3, 4, 5])

In [40]:
arr = np.array([[1,2,3,4],[4,5,6,7],[8,9,5,6]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [8, 9, 5, 6]])

In [41]:
type(arr)

numpy.ndarray

In [42]:
arr.ndim
# give the dimenstion of array

2

In [43]:
arr.size
# give the totol eliment of array

12

In [44]:
arr.shape

(3, 4)

In [45]:
arr.dtype



dtype('int32')

In [46]:
arr2 = np.array([[[12,13,14,15],[16,17,18,19]],[[20,21,22,23],[24,25,26,27]]])
arr2

array([[[12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27]]])

In [47]:
arr2.shape


(2, 2, 4)

In [48]:
arr2.size

16

In [49]:
arr2.ndim

3

In [50]:
list(range(5))
# list(range(5.5)) not work

[0, 1, 2, 3, 4]

In [51]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [52]:
np.arange(6.6,9,.5) # (star,stop,step) (step:(5),(3.3),(.5),(-.3))

array([6.6, 7.1, 7.6, 8.1, 8.6])

In [53]:
print(np.arange(1.1,6.6))
print(np.arange(1,9))

[1.1 2.1 3.1 4.1 5.1 6.1]
[1 2 3 4 5 6 7 8]


In [54]:
# same as range and arange but neture by different 
# linspace (star,stop,elements(divied by equal))
linspace_1 = np.linspace(1,10,10)
print(linspace_1)
# linspace_2 = np.linspace(1,10)  # bydefult 50 data set create
# print(linspace_2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [55]:
zeros_1 = np.zeros((5))
print(zeros_1)

[0. 0. 0. 0. 0.]


In [56]:
zeros_1 = np.zeros((1,2,2,4)) #(Dymenstion,data,rows,columns)  <-----working
zeros_2 = np.zeros((1,2,2,3))
print(zeros_2)

[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]]


In [57]:
# ones_1 = np.ones((2))
# print(ones_1)
# print()

# ones_2 = np.ones((4,3))
# print(ones_2)
# print()

# ones_3 = np.ones((4,2,2))
# print(ones_3)
# print()

# ones_4 = np.ones((4,2,2,2))
# print(ones_4)

In [58]:
empty_1 = np.empty((0))
print(empty_1)

[]


In [59]:
eye_1 = np.eye((3)) # rows x columns  bydefault float numbers.
print(eye_1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
np.linspace([1,5],10,endpoint=False,axis=1)

array([[1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
        2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
        4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
        6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
        8.92, 9.1 , 9.28, 9.46, 9.64, 9.82],
       [5.  , 5.1 , 5.2 , 5.3 , 5.4 , 5.5 , 5.6 , 5.7 , 5.8 , 5.9 , 6.  ,
        6.1 , 6.2 , 6.3 , 6.4 , 6.5 , 6.6 , 6.7 , 6.8 , 6.9 , 7.  , 7.1 ,
        7.2 , 7.3 , 7.4 , 7.5 , 7.6 , 7.7 , 7.8 , 7.9 , 8.  , 8.1 , 8.2 ,
        8.3 , 8.4 , 8.5 , 8.6 , 8.7 , 8.8 , 8.9 , 9.  , 9.1 , 9.2 , 9.3 ,
        9.4 , 9.5 , 9.6 , 9.7 , 9.8 , 9.9 ]])

In [61]:
np.logspace([2],[5],axis=1)

array([[   100.        ,    115.13953993,    132.57113656,
           152.64179672,    175.75106249,    202.35896477,
           232.99518105,    268.26957953,    308.88435965,
           355.64803062,    409.49150624,    471.48663635,
           542.86754393,    625.05519253,    719.685673  ,
           828.64277285,    954.09547635,   1098.54114199,
          1264.85521686,   1456.3484775 ,   1676.83293681,
          1930.69772888,   2222.99648253,   2559.5479227 ,
          2947.05170255,   3393.2217719 ,   3906.93993705,
          4498.43266897,   5179.47467923,   5963.62331659,
          6866.48845004,   7906.04321091,   9102.98177992,
         10481.13134155,  12067.92640639,  13894.95494373,
         15998.58719606,  18420.69969327,  21209.5088792 ,
         24420.53094549,  28117.68697974,  32374.57542818,
         37275.93720315,  42919.34260129,  49417.13361324,
         56898.66029018,  65512.85568596,  75431.20063355,
         86851.13737514, 100000.        ]])

In [62]:
arr_10 = np.linspace(4,7,40)
arr_10

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [63]:
arr_10.ndim

1

In [64]:
arr_10.shape

(40,)

In [65]:
# arr_10.reshape(40,1)
arr_10.reshape(2,1,20)
arr_10

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [66]:
arr_10.ndim

1

In [67]:
arr_10.shape

(40,)

In [68]:
# np.tensordot(1,1)


In [69]:
arr_12 = np.random.rand(5)
arr_12

array([0.86782207, 0.10747713, 0.79259099, 0.63152294, 0.93702796])

In [70]:
arr_13 = np.random.randn(5)
arr_13

array([-1.90642885,  0.38586656,  0.1884779 , -0.29075478, -0.2206831 ])

In [71]:
arr_14 = np.random.randn(2,3,)
arr_14

array([[-0.83316083, -1.21778234, -0.19388387],
       [ 0.12387553, -2.03794729, -0.84630489]])

In [72]:
arr_15 = np.random.randint(5,40,(4,4))
arr_15

array([[32, 20, 38, 11],
       [ 8, 17, 13, 25],
       [27, 38, 19, 18],
       [30, 19, 10, 24]])

In [73]:
arr_16 = np.random.randint(5,40,(4,4))
arr_16

array([[35, 39,  5, 27],
       [30, 10, 33, 10],
       [31, 16, 31, 10],
       [17, 18, 17, 27]])

In [74]:
arr_16.reshape(1,16)
arr_16.reshape(16,1)
arr_16.reshape(8,2)
arr_16.reshape(2,8)


array([[35, 39,  5, 27, 30, 10, 33, 10],
       [31, 16, 31, 10, 17, 18, 17, 27]])

In [75]:
arr_16.reshape(4,-10) # any negitive numbers give. 
arr_16.reshape(2,-10)

array([[35, 39,  5, 27, 30, 10, 33, 10],
       [31, 16, 31, 10, 17, 18, 17, 27]])

In [76]:
arr_16.max()

39

In [77]:
arr_16.min()

5

In [78]:
arr_16.argmin()

2

In [79]:
arr_16.sum()

356

In [80]:
arr_17 = np.random.randint(4,100,(5,5))
arr_17
# find the some data from the set(arr_17)

array([[34, 54, 76, 88, 56],
       [28, 73, 74, 53, 62],
       [12, 89, 37, 83, 87],
       [65, 79, 92, 27, 56],
       [92, 34, 20, 28, 46]])

In [81]:
arr_17[3: ,3:] # show ths some data part(arr_17)


array([[27, 56],
       [28, 46]])

In [82]:
arr_17[:,[1,3]] 

array([[54, 88],
       [73, 53],
       [89, 83],
       [79, 27],
       [34, 28]])

In [83]:
arr_17[[3,2],:]

array([[65, 79, 92, 27, 56],
       [12, 89, 37, 83, 87]])

In [84]:
arr_17[[3,2],[3,2]]

array([27, 37])

In [85]:
arr_17>10  # give a boolen values (codition op.)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [86]:
arr_17[arr_17>10] # values

array([34, 54, 76, 88, 56, 28, 73, 74, 53, 62, 12, 89, 37, 83, 87, 65, 79,
       92, 27, 56, 92, 34, 20, 28, 46])

In [87]:
arr_18_A = np.random.randint(2,4,(3,3))
arr_18_A 

array([[3, 2, 3],
       [2, 3, 3],
       [3, 3, 2]])

In [88]:
arr_18_B = np.random.randint(2,4,(3,3))
arr_18_B

array([[2, 2, 2],
       [2, 3, 3],
       [2, 3, 3]])

In [89]:
arr_18_A * arr_18_B # (multiply for index base) (dymention is same nacessary)

array([[6, 4, 6],
       [4, 9, 9],
       [6, 9, 6]])

In [90]:
arr_18_A @ arr_18_B 

array([[16, 21, 21],
       [16, 22, 22],
       [16, 21, 21]])

In [91]:
arr_18_A**2

array([[9, 4, 9],
       [4, 9, 9],
       [9, 9, 4]], dtype=int32)

In [114]:
# broad casting

In [115]:
arr_19 = np.zeros((3,4))
arr_19

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
arr_20 = np.array([1,2,3,4]) # Shape are some like[(3,)(3,),(4,)(4,),....] or only one
# arr_20 = np.array([5])
arr_20

array([1, 2, 3, 4])

In [94]:
arr_19 + arr_20

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [95]:
arr_21 = np.array([5])

In [96]:
arr_19 + arr_21


array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [102]:
# into clm ******************************************************


array([[7, 8, 9]])

array([[7],
       [8],
       [9]])

In [116]:
arr_23 = np.zeros((3,4))
arr_23

arr_22 = np.array([[7,8,9]])
# change shape
arr_22.reshape(1,3)
arr_22.shape

x = arr_22.reshape(3,1)
x.shape

y = arr_22.T
y.shape

y + arr_23

array([[7., 7., 7., 7.],
       [8., 8., 8., 8.],
       [9., 9., 9., 9.]])

In [ ]:
arr_24 = np.array([[1,2,3,4],[5,6,7,8]])

In [118]:
sqrt = np.sqrt(arr_24)
sqrt

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [120]:
exp = np.exp(arr_24)
exp

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [133]:
log = np.log10(arr_10)
log = np.log(arr_10)
log = np.log2(arr_10)
log

array([2.        , 2.02748074, 2.05444778, 2.08092   , 2.1069152 ,
       2.1324503 , 2.15754128, 2.18220333, 2.20645088, 2.23029762,
       2.25375659, 2.27684021, 2.29956028, 2.32192809, 2.3439544 ,
       2.36564947, 2.38702312, 2.40808474, 2.4288433 , 2.4493074 ,
       2.46948528, 2.48938484, 2.50901365, 2.52837897, 2.5474878 ,
       2.56634682, 2.5849625 , 2.60334103, 2.62148838, 2.63941028,
       2.65711229, 2.67459971, 2.6918777 , 2.70895122, 2.72582504,
       2.74250378, 2.7589919 , 2.77529371, 2.79141338, 2.80735492])